apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "frontend.fullname" . }}
data:
  config.js: |
    {{- range $key, $value := .Values.configValues }}
      window.{{ $key }} = `{{ $value }}`
    {{- end }}